name: Build and Publish Docker Image

on:
  push:
    branches: ["master"]
    paths-ignore: ["**.md", "ext/**"]
  pull_request:
    branches: ["master"]
    paths-ignore: ["**.md", "ext/**"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bancho.py:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker,dest=/tmp/docker.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker
          path: /tmp/docker.tar
