name: Test Application Code
on:
  # TODO: perhaps can optimize this
  push

jobs:
  run-test-suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build application image
        run: docker build -t bancho:latest .

      - name: Start containers
        run: docker-compose up -d bancho mysql redis

      - name: Run tests
        run: docker-compose exec -T bancho /scripts/run_tests.sh

      - name: Stop containers
        if: always()
        run: docker-compose down
