name: Test Application Code
on:
  # TODO: perhaps can optimize this
  push

jobs:
  generate-lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # TODO: make a build & deploy workflow
      # https://stackoverflow.com/a/64733705
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: osuakatsuki/bancho.py:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Start containers
        run: docker-compose up bancho mysql redis

      - name: Run tests
        run: docker-compose run --rm bancho /scripts/run_tests.sh

      - name: Stop containers
        if: always()
        run: docker-compose down
